name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: install
        run: npm install --no-optional
      - name: npm run lint
        run: ./scripts/dev-env/run.sh npm run lint
      - name: lint-rust.sh
        run: |
          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env:latest scripts/lint-rust.sh
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: test-rust.sh
        run: |
          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env:latest scripts/test-rust.sh
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Generate layout.json and update manifest.json
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
          ./scripts/dev-env/run.sh ./scripts/build.sh

          mkdir tmp_flybywire-aircraft-a32nx
          mv flybywire-aircraft-a32nx tmp_flybywire-aircraft-a32nx/
          mv tmp_flybywire-aircraft-a32nx flybywire-aircraft-a32nx
      - uses: actions/upload-artifact@v2
        with:
          name: flybywire-aircraft-a32nx
          path: flybywire-aircraft-a32nx
